version: "3.9"
services:
  ps_db:
    container_name: cms_db
    image: cms_db
    restart: always
    build:
      context: .
      dockerfile:
        Dockerfile-db
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: cms-db