version: '3.9'
services:
  cms_app:
    container_name: cms_app
    image: cms_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}