enum UseType {
  SUB_STRUCTURE,
  SUPER_STRUCTURE,
  DEFAULT_VALUE

}


enum SubStructureUseDescription {
  EXCAVATION_AND_EARTH_WORK,
  CONCRETE_WORK,
  MASONRY_WORK,
  DEFAULT_VALUE
}

enum SuperStructureUseDescription {
  CONCRETE_WORK,
  BLOCK_WORK,
  ROOFING,
  CARPENTRY_AND_JOINERY,
  METAL_WORK,
  PLASTERING_WORK,
  FINISHING_WORK,
  PAINTING_WORK,
  SANITARY_INSTALLATION,
  ELECTRICAL_INSTALLATION,
  MECHANICAL_INSTALLATION,
  DEFAULT_VALUE

}
